sudo: true
language: python
dist: xenial
# env:
python:
  - 3.6
  - 3.7
  - 3.8
# before_install:
#   - sudo apt-get install -y
install:
 - pip install -r requirements.txt
script:
 - tox
after_success:
 - coveralls
